// Code generated by command: go run main.go -out map_simd_amd64.s. DO NOT EDIT.

//go:build amd64.v3 && !nosimd

#include "textflag.h"

DATA ones<>+0(SB)/8, $0x0101010101010101
DATA ones<>+8(SB)/8, $0x0101010101010101
GLOBL ones<>(SB), RODATA|NOPTR, $16

DATA marks<>+0(SB)/8, $0x0000000000000000
DATA marks<>+8(SB)/8, $0x0100000000000000
GLOBL marks<>(SB), RODATA|NOPTR, $16

// func matchAVX2(idx *[16]uint8, p uint8) uint16
// Requires: AVX, AVX2
TEXT ·matchAVX2(SB), NOSPLIT, $0-18
	MOVQ         idx+0(FP), AX
	VPBROADCASTB p+8(FP), X0
	VPCMPEQB     (AX), X0, X0
	VPMOVMSKB    X0, AX
	MOVW         AX, ret+16(FP)
	RET

// func matchEmptyOrSpillmarkAVX2(idx *[16]uint8) uint16
// Requires: AVX
TEXT ·matchEmptyOrSpillmarkAVX2(SB), NOSPLIT, $0-10
	MOVQ      idx+0(FP), AX
	VMOVDQU   (AX), X0
	VPMINUB   ones<>+0(SB), X0, X1
	VPCMPEQB  X0, X1, X1
	VPMOVMSKB X1, AX
	MOVW      AX, ret+8(FP)
	RET

// func cleanupGroupAVX2(idx *[16]uint8, d *[16]uint8, lo uint8, length uint8) int
// Requires: AVX, AVX2, POPCNT
TEXT ·cleanupGroupAVX2(SB), NOSPLIT, $0-32
	MOVQ    d+8(FP), AX
	VMOVDQU (AX), X0

	// Lanes in the expired range: min(x-lo, length) == x-lo.
	VPBROADCASTB lo+16(FP), X1
	VPBROADCASTB length+17(FP), X2
	VPSUBB       X1, X0, X1
	VPMINUB      X2, X1, X2
	VPCMPEQB     X1, X2, X2

	// Lanes that hold no data: min(x, 1) == x. Data and index always agree on which slots these are.
	VPMINUB  ones<>+0(SB), X0, X1
	VPCMPEQB X0, X1, X1

	// The lanes to remove are the expired ones that hold data.
	VPANDN X2, X1, X1

	// POPCNT sets ZF when nothing is removed, and then neither the index nor the data are written.
	VPMOVMSKB X1, CX
	POPCNTL   CX, CX
	MOVQ      CX, ret+24(FP)
	JZ        done

	// Copy the marks into the removed lanes, first for the data, then for the index.
	VPBLENDVB X1, marks<>+0(SB), X0, X0
	VMOVDQU   X0, (AX)
	MOVQ      idx+0(FP), AX
	VMOVDQU   (AX), X0
	VPBLENDVB X1, marks<>+0(SB), X0, X0
	VMOVDQU   X0, (AX)

done:
	RET
